//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integra.Vision.Engine.Host {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Integra.Vision.Engine.Host.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service is already installed or has been marked for deletion..
        /// </summary>
        internal static string AlreadyInstalledService {
            get {
                return ResourceManager.GetString("AlreadyInstalledService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying the configuration file to: &apos;{0}&apos;.
        /// </summary>
        internal static string AppConfigApply {
            get {
                return ResourceManager.GetString("AppConfigApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application configuration file not found. File not found: &apos;{0}&apos;.
        /// </summary>
        internal static string AppConfigFileNotFound {
            get {
                return ResourceManager.GetString("AppConfigFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string AppConfigInvalid {
            get {
                return ResourceManager.GetString("AppConfigInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring the configuration file to: &apos;{0}&apos;.
        /// </summary>
        internal static string AppConfigRestore {
            get {
                return ResourceManager.GetString("AppConfigRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t resolve type &apos;{0}&apos;..
        /// </summary>
        internal static string CannotResolveType {
            get {
                return ResourceManager.GetString("CannotResolveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ -c | -console ]		Run as a console application..
        /// </summary>
        internal static string ConsoleArgDescription {
            get {
                return ResourceManager.GetString("ConsoleArgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integra.Vision.Engine.dll.config.
        /// </summary>
        internal static string EngineAppConfigFileName {
            get {
                return ResourceManager.GetString("EngineAppConfigFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ -p | -path ]			Entry point path..
        /// </summary>
        internal static string EntryPointPathArgDescription {
            get {
                return ResourceManager.GetString("EntryPointPathArgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the file &apos;{0}&apos; into the current AppDomain..
        /// </summary>
        internal static string FileLoadError {
            get {
                return ResourceManager.GetString("FileLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ -h | -help | -? ]		Display list of arguments.
        /// </summary>
        internal static string HelpArgDescription {
            get {
                return ResourceManager.GetString("HelpArgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to integra.vision.engine/hosting.
        /// </summary>
        internal static string HostingConfigurationSection {
            get {
                return ResourceManager.GetString("HostingConfigurationSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ -i | -install ]		Install as a Windows Service..
        /// </summary>
        internal static string InstallArgDescription {
            get {
                return ResourceManager.GetString("InstallArgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integra Vision Engine installation has completed..
        /// </summary>
        internal static string InstalledServiceMessage {
            get {
                return ResourceManager.GetString("InstalledServiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Integra Vision Engine service....
        /// </summary>
        internal static string InstallingServiceMessage {
            get {
                return ResourceManager.GetString("InstallingServiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested operation requires elevation..
        /// </summary>
        internal static string InsufficientAccessPermission {
            get {
                return ResourceManager.GetString("InsufficientAccessPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid arguments. Parsing error..
        /// </summary>
        internal static string InvalidArguments {
            get {
                return ResourceManager.GetString("InvalidArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly builder is a invalid reference..
        /// </summary>
        internal static string InvalidAssemblyBuilder {
            get {
                return ResourceManager.GetString("InvalidAssemblyBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly module is a invalid reference..
        /// </summary>
        internal static string InvalidAssemblyModule {
            get {
                return ResourceManager.GetString("InvalidAssemblyModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to the engine builder is invalid..
        /// </summary>
        internal static string InvalidEngineBuilderRef {
            get {
                return ResourceManager.GetString("InvalidEngineBuilderRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path argument invalid. Must be a valid directory..
        /// </summary>
        internal static string InvalidPathArgument {
            get {
                return ResourceManager.GetString("InvalidPathArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type for dependency resolver..
        /// </summary>
        internal static string InvalidTypeResolver {
            get {
                return ResourceManager.GetString("InvalidTypeResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No action has been taken. Use the argument -h to display help information..
        /// </summary>
        internal static string NoActionTaken {
            get {
                return ResourceManager.GetString("NoActionTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service is not installed..
        /// </summary>
        internal static string NotInstalledService {
            get {
                return ResourceManager.GetString("NotInstalledService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid arguments, only one action is allowed..
        /// </summary>
        internal static string OnlyOneActionAllowed {
            get {
                return ResourceManager.GetString("OnlyOneActionAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred on object wrapper invocation. Type: &apos;{0}&apos; Method: &apos;{1}&apos; Exception: &apos;{2}&apos;.
        /// </summary>
        internal static string RuntimeObjectWrapperInvocationException {
            get {
                return ResourceManager.GetString("RuntimeObjectWrapperInvocationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service is already running..
        /// </summary>
        internal static string ServiceAlreadyStarted {
            get {
                return ResourceManager.GetString("ServiceAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service is already stopped..
        /// </summary>
        internal static string ServiceAlreadyStopped {
            get {
                return ResourceManager.GetString("ServiceAlreadyStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite procesar, analizar y notificar eventos en tiempo real..
        /// </summary>
        internal static string ServiceDescription {
            get {
                return ResourceManager.GetString("ServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integra Vision Engine.
        /// </summary>
        internal static string ServiceDisplayName {
            get {
                return ResourceManager.GetString("ServiceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integra Vision Engine.
        /// </summary>
        internal static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service cannot start because it is in &apos;{0}&apos; state..
        /// </summary>
        internal static string ServiceNotStarted {
            get {
                return ResourceManager.GetString("ServiceNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service could not be started. Check the eventlog for more details..
        /// </summary>
        internal static string ServiceNotStartedTimeout {
            get {
                return ResourceManager.GetString("ServiceNotStartedTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service has started..
        /// </summary>
        internal static string ServiceStarted {
            get {
                return ResourceManager.GetString("ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service has stopped..
        /// </summary>
        internal static string ServiceStopped {
            get {
                return ResourceManager.GetString("ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ -s | -start ]			Start or install and start the service..
        /// </summary>
        internal static string StartArgDescription {
            get {
                return ResourceManager.GetString("StartArgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press enter to end ....
        /// </summary>
        internal static string StopServiceMessage {
            get {
                return ResourceManager.GetString("StopServiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, relatedActivityId={1}.
        /// </summary>
        internal static string TraceListenerBaseTraceMessageFormat {
            get {
                return ResourceManager.GetString("TraceListenerBaseTraceMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to build the Integra Vision Engine. For more information lookup in the systems logs..
        /// </summary>
        internal static string UnableBuildEngine {
            get {
                return ResourceManager.GetString("UnableBuildEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create the instance of the type required as ´{0}&apos;.
        /// </summary>
        internal static string UnableCreateInstanceOf {
            get {
                return ResourceManager.GetString("UnableCreateInstanceOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to abort the Integra Vision Engine Module reference as &apos;{0}&apos;. For more information lookup in the systems logs..
        /// </summary>
        internal static string UnableToAbortModule {
            get {
                return ResourceManager.GetString("UnableToAbortModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to build the Integra Vision Engine Module reference as &apos;{0}&apos;. For more information lookup in the systems logs..
        /// </summary>
        internal static string UnableToBuildModule {
            get {
                return ResourceManager.GetString("UnableToBuildModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start the Integra Vision Engine Module reference as &apos;{0}&apos;. For more information lookup in the systems logs..
        /// </summary>
        internal static string UnableToStartModule {
            get {
                return ResourceManager.GetString("UnableToStartModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to stop the Integra Vision Engine Module reference as &apos;{0}&apos;. For more information lookup in the systems logs..
        /// </summary>
        internal static string UnableToStopModule {
            get {
                return ResourceManager.GetString("UnableToStopModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ -u | -uninstall ]		Uninstall the Windows Service..
        /// </summary>
        internal static string UninstallArgDescription {
            get {
                return ResourceManager.GetString("UninstallArgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integra Vision Engine uninstallation has completed..
        /// </summary>
        internal static string UninstalledServiceMessage {
            get {
                return ResourceManager.GetString("UninstalledServiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling Integra Vision Engine service....
        /// </summary>
        internal static string UninstallingServiceMessage {
            get {
                return ResourceManager.GetString("UninstallingServiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve the bootstrap implementation class..
        /// </summary>
        internal static string UnresolvedBootstrapImpl {
            get {
                return ResourceManager.GetString("UnresolvedBootstrapImpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve the dependency resolver implementation class..
        /// </summary>
        internal static string UnresolvedDepedencyResolverImpl {
            get {
                return ResourceManager.GetString("UnresolvedDepedencyResolverImpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve the dependency required as &apos;{0}&apos;.
        /// </summary>
        internal static string UnresolvedDependency {
            get {
                return ResourceManager.GetString("UnresolvedDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve the module dependency required as &apos;{0}&apos;.
        /// </summary>
        internal static string UnresolvedModuleDependency {
            get {
                return ResourceManager.GetString("UnresolvedModuleDependency", resourceCulture);
            }
        }
    }
}
