//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Globalization;

namespace Integra.Vision.Engine.Host.Resources
{
	///	<summary>
	///	Provides access to string resources.
	///	</summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Integra.Vision.Engine.Host.Resources", "1.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	static partial class SR
	{
		/// <summary>
		/// Looks up a localized string similar to: 
		///	The service is already installed or has been marked for deletion.
		/// </summary>
		public static string AlreadyInstalledService { get { return global::Integra.Vision.Engine.Host.SR.AlreadyInstalledService; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Applying the configuration file to: '{0}'
		/// </summary>
		public static string AppConfigApply(object arg0)
		{
			return string.Format(global::Integra.Vision.Engine.Host.SR.AppConfigApply, new object[]
			{
				arg0,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Application configuration file not found. File not found: '{0}'
		/// </summary>
		public static string AppConfigFileNotFound(object arg0)
		{
			return string.Format(global::Integra.Vision.Engine.Host.SR.AppConfigFileNotFound, new object[]
			{
				arg0,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	The configuration file '{0}' is not valid.
		/// </summary>
		public static string AppConfigInvalid(object arg0)
		{
			return string.Format(global::Integra.Vision.Engine.Host.SR.AppConfigInvalid, new object[]
			{
				arg0,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Restoring the configuration file to: '{0}'
		/// </summary>
		public static string AppConfigRestore(object arg0)
		{
			return string.Format(global::Integra.Vision.Engine.Host.SR.AppConfigRestore, new object[]
			{
				arg0,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Can't resolve type '{0}'.
		/// </summary>
		public static string CannotResolveType(object arg0)
		{
			return string.Format(global::Integra.Vision.Engine.Host.SR.CannotResolveType, new object[]
			{
				arg0,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	[ -c | -console ]		Run as a console application.
		/// </summary>
		public static string ConsoleArgDescription { get { return global::Integra.Vision.Engine.Host.SR.ConsoleArgDescription; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Integra.Vision.Engine.dll.config
		/// </summary>
		public static string EngineAppConfigFileName { get { return global::Integra.Vision.Engine.Host.SR.EngineAppConfigFileName; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	[ -p | -path ]			Entry point path.
		/// </summary>
		public static string EntryPointPathArgDescription { get { return global::Integra.Vision.Engine.Host.SR.EntryPointPathArgDescription; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Unable to load the file '{0}' into the current AppDomain.
		/// </summary>
		public static string FileLoadError(object arg0)
		{
			return string.Format(global::Integra.Vision.Engine.Host.SR.FileLoadError, new object[]
			{
				arg0,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	[ -h | -help | -? ]		Display list of arguments
		/// </summary>
		public static string HelpArgDescription { get { return global::Integra.Vision.Engine.Host.SR.HelpArgDescription; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	integra.vision.engine/hosting
		/// </summary>
		public static string HostingConfigurationSection { get { return global::Integra.Vision.Engine.Host.SR.HostingConfigurationSection; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	[ -i | -install ]		Install as a Windows Service.
		/// </summary>
		public static string InstallArgDescription { get { return global::Integra.Vision.Engine.Host.SR.InstallArgDescription; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Integra Vision Engine installation has completed.
		/// </summary>
		public static string InstalledServiceMessage { get { return global::Integra.Vision.Engine.Host.SR.InstalledServiceMessage; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Installing Integra Vision Engine service...
		/// </summary>
		public static string InstallingServiceMessage { get { return global::Integra.Vision.Engine.Host.SR.InstallingServiceMessage; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	The requested operation requires elevation.
		/// </summary>
		public static string InsufficientAccessPermission { get { return global::Integra.Vision.Engine.Host.SR.InsufficientAccessPermission; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Invalid arguments. Parsing error.
		/// </summary>
		public static string InvalidArguments { get { return global::Integra.Vision.Engine.Host.SR.InvalidArguments; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Assembly builder is a invalid reference.
		/// </summary>
		public static string InvalidAssemblyBuilder { get { return global::Integra.Vision.Engine.Host.SR.InvalidAssemblyBuilder; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Assembly module is a invalid reference.
		/// </summary>
		public static string InvalidAssemblyModule { get { return global::Integra.Vision.Engine.Host.SR.InvalidAssemblyModule; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Reference to the engine builder is invalid.
		/// </summary>
		public static string InvalidEngineBuilderRef { get { return global::Integra.Vision.Engine.Host.SR.InvalidEngineBuilderRef; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Path argument invalid. Must be a valid directory.
		/// </summary>
		public static string InvalidPathArgument { get { return global::Integra.Vision.Engine.Host.SR.InvalidPathArgument; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Invalid type for dependency resolver.
		/// </summary>
		public static string InvalidTypeResolver { get { return global::Integra.Vision.Engine.Host.SR.InvalidTypeResolver; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	No action has been taken. Use the argument -h to display help information.
		/// </summary>
		public static string NoActionTaken { get { return global::Integra.Vision.Engine.Host.SR.NoActionTaken; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	The service is not installed.
		/// </summary>
		public static string NotInstalledService { get { return global::Integra.Vision.Engine.Host.SR.NotInstalledService; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Invalid arguments, only one action is allowed.
		/// </summary>
		public static string OnlyOneActionAllowed { get { return global::Integra.Vision.Engine.Host.SR.OnlyOneActionAllowed; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	An error ocurred on object wrapper invocation. Type: '{0}' Method: '{1}' Exception: '{2}'
		/// </summary>
		public static string RuntimeObjectWrapperInvocationException(object arg0, object arg1, object arg2)
		{
			return string.Format(global::Integra.Vision.Engine.Host.SR.RuntimeObjectWrapperInvocationException, new object[]
			{
				arg0,
				arg1,
				arg2,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	The service is already running.
		/// </summary>
		public static string ServiceAlreadyStarted { get { return global::Integra.Vision.Engine.Host.SR.ServiceAlreadyStarted; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	The service is already stopped.
		/// </summary>
		public static string ServiceAlreadyStopped { get { return global::Integra.Vision.Engine.Host.SR.ServiceAlreadyStopped; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Permite procesar, analizar y notificar eventos en tiempo real.
		/// </summary>
		public static string ServiceDescription { get { return global::Integra.Vision.Engine.Host.SR.ServiceDescription; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Integra Vision Engine
		/// </summary>
		public static string ServiceDisplayName { get { return global::Integra.Vision.Engine.Host.SR.ServiceDisplayName; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Integra Vision Engine
		/// </summary>
		public static string ServiceName { get { return global::Integra.Vision.Engine.Host.SR.ServiceName; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	The service cannot start because it is in '{0}' state.
		/// </summary>
		public static string ServiceNotStarted(object arg0)
		{
			return string.Format(global::Integra.Vision.Engine.Host.SR.ServiceNotStarted, new object[]
			{
				arg0,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	The service could not be started. Check the eventlog for more details.
		/// </summary>
		public static string ServiceNotStartedTimeout { get { return global::Integra.Vision.Engine.Host.SR.ServiceNotStartedTimeout; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	The service has started.
		/// </summary>
		public static string ServiceStarted { get { return global::Integra.Vision.Engine.Host.SR.ServiceStarted; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	The service has stopped.
		/// </summary>
		public static string ServiceStopped { get { return global::Integra.Vision.Engine.Host.SR.ServiceStopped; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	[ -s | -start ]			Start or install and start the service.
		/// </summary>
		public static string StartArgDescription { get { return global::Integra.Vision.Engine.Host.SR.StartArgDescription; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Press enter to end ...
		/// </summary>
		public static string StopServiceMessage { get { return global::Integra.Vision.Engine.Host.SR.StopServiceMessage; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	{0}, relatedActivityId={1}
		/// </summary>
		public static string TraceListenerBaseTraceMessageFormat(object arg0, object arg1)
		{
			return string.Format(global::Integra.Vision.Engine.Host.SR.TraceListenerBaseTraceMessageFormat, new object[]
			{
				arg0,
				arg1,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Unable to build the Integra Vision Engine. For more information lookup in the systems logs.
		/// </summary>
		public static string UnableBuildEngine { get { return global::Integra.Vision.Engine.Host.SR.UnableBuildEngine; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Could not create the instance of the type required as ´{0}'
		/// </summary>
		public static string UnableCreateInstanceOf(object arg0)
		{
			return string.Format(global::Integra.Vision.Engine.Host.SR.UnableCreateInstanceOf, new object[]
			{
				arg0,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Unable to abort the Integra Vision Engine Module reference as '{0}'. For more information lookup in the systems logs.
		/// </summary>
		public static string UnableToAbortModule(object arg0)
		{
			return string.Format(global::Integra.Vision.Engine.Host.SR.UnableToAbortModule, new object[]
			{
				arg0,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Unable to build the Integra Vision Engine Module reference as '{0}'. For more information lookup in the systems logs.
		/// </summary>
		public static string UnableToBuildModule(object arg0)
		{
			return string.Format(global::Integra.Vision.Engine.Host.SR.UnableToBuildModule, new object[]
			{
				arg0,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Unable to start the Integra Vision Engine Module reference as '{0}'. For more information lookup in the systems logs.
		/// </summary>
		public static string UnableToStartModule(object arg0)
		{
			return string.Format(global::Integra.Vision.Engine.Host.SR.UnableToStartModule, new object[]
			{
				arg0,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Unable to stop the Integra Vision Engine Module reference as '{0}'. For more information lookup in the systems logs.
		/// </summary>
		public static string UnableToStopModule(object arg0)
		{
			return string.Format(global::Integra.Vision.Engine.Host.SR.UnableToStopModule, new object[]
			{
				arg0,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	[ -u | -uninstall ]		Uninstall the Windows Service.
		/// </summary>
		public static string UninstallArgDescription { get { return global::Integra.Vision.Engine.Host.SR.UninstallArgDescription; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Integra Vision Engine uninstallation has completed.
		/// </summary>
		public static string UninstalledServiceMessage { get { return global::Integra.Vision.Engine.Host.SR.UninstalledServiceMessage; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Uninstalling Integra Vision Engine service...
		/// </summary>
		public static string UninstallingServiceMessage { get { return global::Integra.Vision.Engine.Host.SR.UninstallingServiceMessage; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Could not resolve the bootstrap implementation class.
		/// </summary>
		public static string UnresolvedBootstrapImpl { get { return global::Integra.Vision.Engine.Host.SR.UnresolvedBootstrapImpl; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Could not resolve the dependency resolver implementation class.
		/// </summary>
		public static string UnresolvedDepedencyResolverImpl { get { return global::Integra.Vision.Engine.Host.SR.UnresolvedDepedencyResolverImpl; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Could not resolve the dependency required as '{0}'
		/// </summary>
		public static string UnresolvedDependency(object arg0)
		{
			return string.Format(global::Integra.Vision.Engine.Host.SR.UnresolvedDependency, new object[]
			{
				arg0,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Could not resolve the module dependency required as '{0}'
		/// </summary>
		public static string UnresolvedModuleDependency(object arg0)
		{
			return string.Format(global::Integra.Vision.Engine.Host.SR.UnresolvedModuleDependency, new object[]
			{
				arg0,
			});
		}
	}
}

