//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Globalization;

namespace Integra.Vision.Engine.Host.Diagnostics.Resources
{
	///	<summary>
	///	Provides access to string resources.
	///	</summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Integra.Vision.Engine.Host.Resources", "1.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	static partial class SR
	{
		/// <summary>
		/// Looks up a localized string similar to: 
		///	The dependency resolver type in the configuration file can't be activated.
		/// </summary>
		public static string DependecyResolverTypeCantBeActivated { get { return global::Integra.Vision.Engine.Host.Diagnostics.SR.DependecyResolverTypeCantBeActivated; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Hosting configuration section not found.
		/// </summary>
		public static string HostingConfigurationNotFound { get { return global::Integra.Vision.Engine.Host.Diagnostics.SR.HostingConfigurationNotFound; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Integra Vision Engine Runtime has started.
		/// </summary>
		public static string RuntimeStarted { get { return global::Integra.Vision.Engine.Host.Diagnostics.SR.RuntimeStarted; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Starting Integra Vision Engine Runtime...
		/// </summary>
		public static string RuntimeStarting { get { return global::Integra.Vision.Engine.Host.Diagnostics.SR.RuntimeStarting; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Integra.Vision.Engine.Host
		/// </summary>
		public static string RuntimeTraceSourceName { get { return global::Integra.Vision.Engine.Host.Diagnostics.SR.RuntimeTraceSourceName; } }
	}
}

