//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integra.Vision.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Integra.Vision.Language.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} {3} {4} {5} {6} {7} {8}.
        /// </summary>
        internal static string AdapterNodeText {
            get {
                return ResourceManager.GetString("AdapterNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adapter.
        /// </summary>
        internal static string AdapterObject {
            get {
                return ResourceManager.GetString("AdapterObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adapter.
        /// </summary>
        internal static string AdapterProperty {
            get {
                return ResourceManager.GetString("AdapterProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdapterType.
        /// </summary>
        internal static string AdapterTypeRole {
            get {
                return ResourceManager.GetString("AdapterTypeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to agent.
        /// </summary>
        internal static string AgentProperty {
            get {
                return ResourceManager.GetString("AgentProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplyWindow.
        /// </summary>
        internal static string ApplyWindowRole {
            get {
                return ResourceManager.GetString("ApplyWindowRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} {3} {4}.
        /// </summary>
        internal static string AssemblyNodeText {
            get {
                return ResourceManager.GetString("AssemblyNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assembly.
        /// </summary>
        internal static string AssemblyObject {
            get {
                return ResourceManager.GetString("AssemblyObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssemblyPath.
        /// </summary>
        internal static string AssemblyPathRole {
            get {
                return ResourceManager.GetString("AssemblyPathRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        internal static string BodyRole {
            get {
                return ResourceManager.GetString("BodyRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataType.
        /// </summary>
        internal static string DataTypeProperty {
            get {
                return ResourceManager.GetString("DataTypeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependence.
        /// </summary>
        internal static string DependenceRole {
            get {
                return ResourceManager.GetString("DependenceRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}.
        /// </summary>
        internal static string DropNodeText {
            get {
                return ResourceManager.GetString("DropNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento.
        /// </summary>
        internal static string EventRole {
            get {
                return ResourceManager.GetString("EventRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string FromRole {
            get {
                return ResourceManager.GetString("FromRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string IdentifierRole {
            get {
                return ResourceManager.GetString("IdentifierRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception has ocurred on command interpretation. The inner exception may contain more information..
        /// </summary>
        internal static string InterpretationException {
            get {
                return ResourceManager.GetString("InterpretationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        internal static string JoinRole {
            get {
                return ResourceManager.GetString("JoinRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.
        /// </summary>
        internal static string MessageProperty {
            get {
                return ResourceManager.GetString("MessageProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string NameProperty {
            get {
                return ResourceManager.GetString("NameProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        internal static string ObjectRole {
            get {
                return ResourceManager.GetString("ObjectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string OnRole {
            get {
                return ResourceManager.GetString("OnRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} {3} {4}.
        /// </summary>
        internal static string ParameterNodeText {
            get {
                return ResourceManager.GetString("ParameterNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string ParametersRole {
            get {
                return ResourceManager.GetString("ParametersRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordRole {
            get {
                return ResourceManager.GetString("PasswordRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string PrpoertyProperty {
            get {
                return ResourceManager.GetString("PrpoertyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string ReferenceRole {
            get {
                return ResourceManager.GetString("ReferenceRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adapter.
        /// </summary>
        internal static string ReservedWordAdapter {
            get {
                return ResourceManager.GetString("ReservedWordAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deny.
        /// </summary>
        internal static string ReservedWordDeny {
            get {
                return ResourceManager.GetString("ReservedWordDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to engine.
        /// </summary>
        internal static string ReservedWordEngine {
            get {
                return ResourceManager.GetString("ReservedWordEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grant.
        /// </summary>
        internal static string ReservedWordGrant {
            get {
                return ResourceManager.GetString("ReservedWordGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to revoke.
        /// </summary>
        internal static string ReservedWordRevoke {
            get {
                return ResourceManager.GetString("ReservedWordRevoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to role.
        /// </summary>
        internal static string ReservedWordRole {
            get {
                return ResourceManager.GetString("ReservedWordRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to source.
        /// </summary>
        internal static string ReservedWordSource {
            get {
                return ResourceManager.GetString("ReservedWordSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start.
        /// </summary>
        internal static string ReservedWordStart {
            get {
                return ResourceManager.GetString("ReservedWordStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop.
        /// </summary>
        internal static string ReservedWordStop {
            get {
                return ResourceManager.GetString("ReservedWordStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stream.
        /// </summary>
        internal static string ReservedWordStream {
            get {
                return ResourceManager.GetString("ReservedWordStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trigger.
        /// </summary>
        internal static string ReservedWordTrigger {
            get {
                return ResourceManager.GetString("ReservedWordTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        internal static string ReservedWordUser {
            get {
                return ResourceManager.GetString("ReservedWordUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}.
        /// </summary>
        internal static string RoleNodeText {
            get {
                return ResourceManager.GetString("RoleNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to role.
        /// </summary>
        internal static string RoleObject {
            get {
                return ResourceManager.GetString("RoleObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecureObjectName.
        /// </summary>
        internal static string SecureObjectNameRole {
            get {
                return ResourceManager.GetString("SecureObjectNameRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecureObject.
        /// </summary>
        internal static string SecureObjectProperty {
            get {
                return ResourceManager.GetString("SecureObjectProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string SelectRole {
            get {
                return ResourceManager.GetString("SelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} {3}.
        /// </summary>
        internal static string SendNodeText {
            get {
                return ResourceManager.GetString("SendNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string SendRole {
            get {
                return ResourceManager.GetString("SendRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} {3} {4} {5}.
        /// </summary>
        internal static string SourceNodeText {
            get {
                return ResourceManager.GetString("SourceNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to source.
        /// </summary>
        internal static string SourceObject {
            get {
                return ResourceManager.GetString("SourceObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}.
        /// </summary>
        internal static string StartStopNodeText {
            get {
                return ResourceManager.GetString("StartStopNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string StatusProperty {
            get {
                return ResourceManager.GetString("StatusProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} {3} {4} {5} {6}.
        /// </summary>
        internal static string StreamNodeText1 {
            get {
                return ResourceManager.GetString("StreamNodeText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} {3} {4} {5} {6} {7} {8} {9}.
        /// </summary>
        internal static string StreamNodeText2 {
            get {
                return ResourceManager.GetString("StreamNodeText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stream.
        /// </summary>
        internal static string StreamObject {
            get {
                return ResourceManager.GetString("StreamObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Syntax error: {0}. Line {1}, column {2}.
        /// </summary>
        internal static string SyntaxError {
            get {
                return ResourceManager.GetString("SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timestamp.
        /// </summary>
        internal static string TimestampProperty {
            get {
                return ResourceManager.GetString("TimestampProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string ToProperty {
            get {
                return ResourceManager.GetString("ToProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} {3} {4} {5}.
        /// </summary>
        internal static string TriggerNodeText1 {
            get {
                return ResourceManager.GetString("TriggerNodeText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} {3} {4} {5} {6}.
        /// </summary>
        internal static string TriggerNodeText2 {
            get {
                return ResourceManager.GetString("TriggerNodeText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trigger.
        /// </summary>
        internal static string TriggerObject {
            get {
                return ResourceManager.GetString("TriggerObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string TypeRole {
            get {
                return ResourceManager.GetString("TypeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserDefinedObject.
        /// </summary>
        internal static string UserDefinedObjectProperty {
            get {
                return ResourceManager.GetString("UserDefinedObjectProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserDefinedObject.
        /// </summary>
        internal static string UserDefinedObjectRole {
            get {
                return ResourceManager.GetString("UserDefinedObjectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} {3} {4} = {5}, {6} = {7}.
        /// </summary>
        internal static string UserNodeText {
            get {
                return ResourceManager.GetString("UserNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        internal static string UserObject {
            get {
                return ResourceManager.GetString("UserObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string ValueProperty {
            get {
                return ResourceManager.GetString("ValueProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string ValueRole {
            get {
                return ResourceManager.GetString("ValueRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where.
        /// </summary>
        internal static string WhereRole {
            get {
                return ResourceManager.GetString("WhereRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With.
        /// </summary>
        internal static string WithRole {
            get {
                return ResourceManager.GetString("WithRole", resourceCulture);
            }
        }
    }
}
