//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Globalization;

namespace Integra.Vision.Language.Resources
{
	///	<summary>
	///	Provides access to string resources.
	///	</summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Integra.Vision.Language.Resources", "1.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	static partial class SR
	{
		/// <summary>
		/// Looks up a localized string similar to: 
		///	{0} {1} {2} {3} {4} {5} {6} {7} {8}
		/// </summary>
		public static string AdapterNodeText(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8)
		{
			return string.Format(global::Integra.Vision.Language.SR.AdapterNodeText, new object[]
			{
				arg0,
				arg1,
				arg2,
				arg3,
				arg4,
				arg5,
				arg6,
				arg7,
				arg8,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	adapter
		/// </summary>
		public static string AdapterObject { get { return global::Integra.Vision.Language.SR.AdapterObject; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	adapter
		/// </summary>
		public static string AdapterProperty { get { return global::Integra.Vision.Language.SR.AdapterProperty; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	AdapterType
		/// </summary>
		public static string AdapterTypeRole { get { return global::Integra.Vision.Language.SR.AdapterTypeRole; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	agent
		/// </summary>
		public static string AgentProperty { get { return global::Integra.Vision.Language.SR.AgentProperty; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	ApplyWindow
		/// </summary>
		public static string ApplyWindowRole { get { return global::Integra.Vision.Language.SR.ApplyWindowRole; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	{0} {1} {2} {3} {4}
		/// </summary>
		public static string AssemblyNodeText(object arg0, object arg1, object arg2, object arg3, object arg4)
		{
			return string.Format(global::Integra.Vision.Language.SR.AssemblyNodeText, new object[]
			{
				arg0,
				arg1,
				arg2,
				arg3,
				arg4,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	assembly
		/// </summary>
		public static string AssemblyObject { get { return global::Integra.Vision.Language.SR.AssemblyObject; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	AssemblyPath
		/// </summary>
		public static string AssemblyPathRole { get { return global::Integra.Vision.Language.SR.AssemblyPathRole; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Body
		/// </summary>
		public static string BodyRole { get { return global::Integra.Vision.Language.SR.BodyRole; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	DataType
		/// </summary>
		public static string DataTypeProperty { get { return global::Integra.Vision.Language.SR.DataTypeProperty; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Dependence
		/// </summary>
		public static string DependenceRole { get { return global::Integra.Vision.Language.SR.DependenceRole; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	{0} {1} {2}
		/// </summary>
		public static string DropNodeText(object arg0, object arg1, object arg2)
		{
			return string.Format(global::Integra.Vision.Language.SR.DropNodeText, new object[]
			{
				arg0,
				arg1,
				arg2,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Evento
		/// </summary>
		public static string EventRole { get { return global::Integra.Vision.Language.SR.EventRole; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	From
		/// </summary>
		public static string FromRole { get { return global::Integra.Vision.Language.SR.FromRole; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Identifier
		/// </summary>
		public static string IdentifierRole { get { return global::Integra.Vision.Language.SR.IdentifierRole; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	An exception has ocurred on command interpretation. The inner exception may contain more information.
		/// </summary>
		public static string InterpretationException { get { return global::Integra.Vision.Language.SR.InterpretationException; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Join
		/// </summary>
		public static string JoinRole { get { return global::Integra.Vision.Language.SR.JoinRole; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	message
		/// </summary>
		public static string MessageProperty { get { return global::Integra.Vision.Language.SR.MessageProperty; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	name
		/// </summary>
		public static string NameProperty { get { return global::Integra.Vision.Language.SR.NameProperty; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Object
		/// </summary>
		public static string ObjectRole { get { return global::Integra.Vision.Language.SR.ObjectRole; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	On
		/// </summary>
		public static string OnRole { get { return global::Integra.Vision.Language.SR.OnRole; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	{0} {1} {2} {3} {4}
		/// </summary>
		public static string ParameterNodeText(object arg0, object arg1, object arg2, object arg3, object arg4)
		{
			return string.Format(global::Integra.Vision.Language.SR.ParameterNodeText, new object[]
			{
				arg0,
				arg1,
				arg2,
				arg3,
				arg4,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Parameters
		/// </summary>
		public static string ParametersRole { get { return global::Integra.Vision.Language.SR.ParametersRole; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Password
		/// </summary>
		public static string PasswordRole { get { return global::Integra.Vision.Language.SR.PasswordRole; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Property
		/// </summary>
		public static string PrpoertyProperty { get { return global::Integra.Vision.Language.SR.PrpoertyProperty; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Reference
		/// </summary>
		public static string ReferenceRole { get { return global::Integra.Vision.Language.SR.ReferenceRole; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	adapter
		/// </summary>
		public static string ReservedWordAdapter { get { return global::Integra.Vision.Language.SR.ReservedWordAdapter; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	deny
		/// </summary>
		public static string ReservedWordDeny { get { return global::Integra.Vision.Language.SR.ReservedWordDeny; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	engine
		/// </summary>
		public static string ReservedWordEngine { get { return global::Integra.Vision.Language.SR.ReservedWordEngine; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	grant
		/// </summary>
		public static string ReservedWordGrant { get { return global::Integra.Vision.Language.SR.ReservedWordGrant; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	revoke
		/// </summary>
		public static string ReservedWordRevoke { get { return global::Integra.Vision.Language.SR.ReservedWordRevoke; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	role
		/// </summary>
		public static string ReservedWordRole { get { return global::Integra.Vision.Language.SR.ReservedWordRole; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	source
		/// </summary>
		public static string ReservedWordSource { get { return global::Integra.Vision.Language.SR.ReservedWordSource; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	start
		/// </summary>
		public static string ReservedWordStart { get { return global::Integra.Vision.Language.SR.ReservedWordStart; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	stop
		/// </summary>
		public static string ReservedWordStop { get { return global::Integra.Vision.Language.SR.ReservedWordStop; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	stream
		/// </summary>
		public static string ReservedWordStream { get { return global::Integra.Vision.Language.SR.ReservedWordStream; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	trigger
		/// </summary>
		public static string ReservedWordTrigger { get { return global::Integra.Vision.Language.SR.ReservedWordTrigger; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	user
		/// </summary>
		public static string ReservedWordUser { get { return global::Integra.Vision.Language.SR.ReservedWordUser; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	{0} {1} {2}
		/// </summary>
		public static string RoleNodeText(object arg0, object arg1, object arg2)
		{
			return string.Format(global::Integra.Vision.Language.SR.RoleNodeText, new object[]
			{
				arg0,
				arg1,
				arg2,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	role
		/// </summary>
		public static string RoleObject { get { return global::Integra.Vision.Language.SR.RoleObject; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	SecureObjectName
		/// </summary>
		public static string SecureObjectNameRole { get { return global::Integra.Vision.Language.SR.SecureObjectNameRole; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	SecureObject
		/// </summary>
		public static string SecureObjectProperty { get { return global::Integra.Vision.Language.SR.SecureObjectProperty; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Select
		/// </summary>
		public static string SelectRole { get { return global::Integra.Vision.Language.SR.SelectRole; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	{0} {1} {2} {3}
		/// </summary>
		public static string SendNodeText(object arg0, object arg1, object arg2, object arg3)
		{
			return string.Format(global::Integra.Vision.Language.SR.SendNodeText, new object[]
			{
				arg0,
				arg1,
				arg2,
				arg3,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Send
		/// </summary>
		public static string SendRole { get { return global::Integra.Vision.Language.SR.SendRole; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	{0} {1} {2} {3} {4} {5}
		/// </summary>
		public static string SourceNodeText(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5)
		{
			return string.Format(global::Integra.Vision.Language.SR.SourceNodeText, new object[]
			{
				arg0,
				arg1,
				arg2,
				arg3,
				arg4,
				arg5,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	source
		/// </summary>
		public static string SourceObject { get { return global::Integra.Vision.Language.SR.SourceObject; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	{0} {1} {2}
		/// </summary>
		public static string StartStopNodeText(object arg0, object arg1, object arg2)
		{
			return string.Format(global::Integra.Vision.Language.SR.StartStopNodeText, new object[]
			{
				arg0,
				arg1,
				arg2,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Status
		/// </summary>
		public static string StatusProperty { get { return global::Integra.Vision.Language.SR.StatusProperty; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	{0} {1} {2} {3} {4} {5} {6}
		/// </summary>
		public static string StreamNodeText1(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6)
		{
			return string.Format(global::Integra.Vision.Language.SR.StreamNodeText1, new object[]
			{
				arg0,
				arg1,
				arg2,
				arg3,
				arg4,
				arg5,
				arg6,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	{0} {1} {2} {3} {4} {5} {6} {7} {8} {9}
		/// </summary>
		public static string StreamNodeText2(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, object arg8, object arg9)
		{
			return string.Format(global::Integra.Vision.Language.SR.StreamNodeText2, new object[]
			{
				arg0,
				arg1,
				arg2,
				arg3,
				arg4,
				arg5,
				arg6,
				arg7,
				arg8,
				arg9,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	stream
		/// </summary>
		public static string StreamObject { get { return global::Integra.Vision.Language.SR.StreamObject; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Invalid input. Syntax error: {0}. Line {1}, column {2}
		/// </summary>
		public static string SyntaxError(object arg0, object arg1, object arg2)
		{
			return string.Format(global::Integra.Vision.Language.SR.SyntaxError, new object[]
			{
				arg0,
				arg1,
				arg2,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	timestamp
		/// </summary>
		public static string TimestampProperty { get { return global::Integra.Vision.Language.SR.TimestampProperty; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	To
		/// </summary>
		public static string ToProperty { get { return global::Integra.Vision.Language.SR.ToProperty; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	{0} {1} {2} {3} {4} {5}
		/// </summary>
		public static string TriggerNodeText1(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5)
		{
			return string.Format(global::Integra.Vision.Language.SR.TriggerNodeText1, new object[]
			{
				arg0,
				arg1,
				arg2,
				arg3,
				arg4,
				arg5,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	{0} {1} {2} {3} {4} {5} {6}
		/// </summary>
		public static string TriggerNodeText2(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6)
		{
			return string.Format(global::Integra.Vision.Language.SR.TriggerNodeText2, new object[]
			{
				arg0,
				arg1,
				arg2,
				arg3,
				arg4,
				arg5,
				arg6,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	trigger
		/// </summary>
		public static string TriggerObject { get { return global::Integra.Vision.Language.SR.TriggerObject; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Tipo
		/// </summary>
		public static string TypeRole { get { return global::Integra.Vision.Language.SR.TypeRole; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	UserDefinedObject
		/// </summary>
		public static string UserDefinedObjectProperty { get { return global::Integra.Vision.Language.SR.UserDefinedObjectProperty; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	UserDefinedObject
		/// </summary>
		public static string UserDefinedObjectRole { get { return global::Integra.Vision.Language.SR.UserDefinedObjectRole; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	{0} {1} {2} {3} {4} = {5}, {6} = {7}
		/// </summary>
		public static string UserNodeText(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7)
		{
			return string.Format(global::Integra.Vision.Language.SR.UserNodeText, new object[]
			{
				arg0,
				arg1,
				arg2,
				arg3,
				arg4,
				arg5,
				arg6,
				arg7,
			});
		}
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	user
		/// </summary>
		public static string UserObject { get { return global::Integra.Vision.Language.SR.UserObject; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Value
		/// </summary>
		public static string ValueProperty { get { return global::Integra.Vision.Language.SR.ValueProperty; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Valor
		/// </summary>
		public static string ValueRole { get { return global::Integra.Vision.Language.SR.ValueRole; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Where
		/// </summary>
		public static string WhereRole { get { return global::Integra.Vision.Language.SR.WhereRole; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	With
		/// </summary>
		public static string WithRole { get { return global::Integra.Vision.Language.SR.WithRole; } }
	}
}

