//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Globalization;

namespace Integra.Vision.Diagnostics.Resources
{
	///	<summary>
	///	Provides access to string resources.
	///	</summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Integra.Vision.Diagnostics.Resources", "1.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	static partial class SR
	{
		/// <summary>
		/// Looks up a localized string similar to: 
		///	AppDomain unloading.
		/// </summary>
		public static string TraceAppDomainUnload { get { return global::Integra.Vision.Diagnostics.SR.TraceAppDomainUnload; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Wrote to the EventLog.
		/// </summary>
		public static string TraceEventLog { get { return global::Integra.Vision.Diagnostics.SR.TraceEventLog; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Unhandled exception.
		/// </summary>
		public static string UnhandledException { get { return global::Integra.Vision.Diagnostics.SR.UnhandledException; } }
	
		/// <summary>
		/// Looks up a localized string similar to: 
		///	Unobserved task exception.
		/// </summary>
		public static string UnobservedTaskException { get { return global::Integra.Vision.Diagnostics.SR.UnobservedTaskException; } }
	}
}

