//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integra.Vision.Engine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Integra.Vision.Engine.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boot fail, because the response is empty..
        /// </summary>
        internal static string BootResponseEmpty {
            get {
                return ResourceManager.GetString("BootResponseEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boot fail, because the response is invalid. The type of response is {0}..
        /// </summary>
        internal static string BootResponseInvalid {
            get {
                return ResourceManager.GetString("BootResponseInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boot fail, because the response is null..
        /// </summary>
        internal static string BootResponseNull {
            get {
                return ResourceManager.GetString("BootResponseNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIIJNwIBAzCCCPcGCSqGSIb3DQEHAaCCCOgEggjkMIII4DCCBgkGCSqGSIb3DQEHAaCCBfoEggX2MIIF8jCCBe4GCyqGSIb3DQEMCgECoIIE/jCCBPowHAYKKoZIhvcNAQwBAzAOBAi4EilLEEMwPQICB9AEggTYh4SN7nxVCU6gcqWP5pm9DeAedTH9qZAZEI7gV7lwwc1nUN4eAL4epjGkbNhUiWa8BtkqmGiYgSbiJKaiQMbvH43uCup/RWdz/1+tV16mgEm8jy2qN7QL+OVJ36GGuD4Wqo6M9DvrEPDhhBNqpkLN2+4T8D1u21ftL3Xx/fZeH0qZ9c4egDGKbSqkdwsumUNJDLVJ6VzZYEwXTm9BV7NaTgtW3TCdLD2mTyhd53pk6iCoFd0h1onCHCB/CVMmJWRfHDQmqC7AqxjBuLlJ5AKymSoxd7Bc3Sh3Y9zaIt/9XrXSPuW9GU+cwu1pBhLxKkPAqLF0eFzgaeyZVJLdr6Zrg2iANCpSxd94 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CertificateData {
            get {
                return ResourceManager.GetString("CertificateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://Integra.Vision.Engine/.
        /// </summary>
        internal static string CommandServerDataContractNS {
            get {
                return ResourceManager.GetString("CommandServerDataContractNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://Integra.Vision.Engine/.
        /// </summary>
        internal static string CommandServerServiceContractNameSpace {
            get {
                return ResourceManager.GetString("CommandServerServiceContractNameSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandServer.
        /// </summary>
        internal static string CommandServerServiceName {
            get {
                return ResourceManager.GetString("CommandServerServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row value is not valid..
        /// </summary>
        internal static string DataSetRowValueValidationError {
            get {
                return ResourceManager.GetString("DataSetRowValueValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled error on row validation..
        /// </summary>
        internal static string DataSetUnhandledException {
            get {
                return ResourceManager.GetString("DataSetUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine configuration section not found..
        /// </summary>
        internal static string EngineConfigurationNotFound {
            get {
                return ResourceManager.GetString("EngineConfigurationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to integra.vision.engine/engine.
        /// </summary>
        internal static string EngineConfigurationSection {
            get {
                return ResourceManager.GetString("EngineConfigurationSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration exception ocurred. The inner exception may contain more information..
        /// </summary>
        internal static string EnumerationException {
            get {
                return ResourceManager.GetString("EnumerationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerator is not implement for command.
        /// </summary>
        internal static string EnumeratorNotImplemented {
            get {
                return ResourceManager.GetString("EnumeratorNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExecuteReply.
        /// </summary>
        internal static string ExecuteReplyAction {
            get {
                return ResourceManager.GetString("ExecuteReplyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception has ocurred on command interpretation. The inner exception may contain more information..
        /// </summary>
        internal static string InterpretationException {
            get {
                return ResourceManager.GetString("InterpretationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is a invalid type for use as factory for action filters..
        /// </summary>
        internal static string InvalidActionFilterFactoryType {
            get {
                return ResourceManager.GetString("InvalidActionFilterFactoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid access to command element collection.
        /// </summary>
        internal static string InvalidCommandElementCollection {
            get {
                return ResourceManager.GetString("InvalidCommandElementCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is a invalid type for use as factory for dispatch filters..
        /// </summary>
        internal static string InvalidDispatchFilterFactoryType {
            get {
                return ResourceManager.GetString("InvalidDispatchFilterFactoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid access to command plan.
        /// </summary>
        internal static string InvalidPlanAccess {
            get {
                return ResourceManager.GetString("InvalidPlanAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestType.
        /// </summary>
        internal static string RequestTypeHeaderName {
            get {
                return ResourceManager.GetString("RequestTypeHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to httpSource.
        /// </summary>
        internal static string SourceHttpType {
            get {
                return ResourceManager.GetString("SourceHttpType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Syntax error: {0}. Line {1}, column {2}.
        /// </summary>
        internal static string SyntaxError {
            get {
                return ResourceManager.GetString("SyntaxError", resourceCulture);
            }
        }
    }
}
