//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Integra.Vision.Engine.Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class SR {
        
        /// <summary>
        ///   Looks up a localized string similar to: Enumeration exception ocurred. The inner exception may contain more information.
        /// </summary>
        public static string EnumerationException([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Integra.Vision.Engine.Resources.SR.EnumerationException;
            }
            return global::Integra.Vision.Engine.Resources.SR.ResourceManager.GetString("EnumerationException", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Enumerator is not implement for command
        /// </summary>
        public static string EnumeratorNotImplemented([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Integra.Vision.Engine.Resources.SR.EnumeratorNotImplemented;
            }
            return global::Integra.Vision.Engine.Resources.SR.ResourceManager.GetString("EnumeratorNotImplemented", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: An exception has ocurred on command interpretation. The inner exception may contain more information.
        /// </summary>
        public static string InterpretationException([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Integra.Vision.Engine.Resources.SR.InterpretationException;
            }
            return global::Integra.Vision.Engine.Resources.SR.ResourceManager.GetString("InterpretationException", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Invalid access to command element collection
        /// </summary>
        public static string InvalidCommandElementCollection([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Integra.Vision.Engine.Resources.SR.InvalidCommandElementCollection;
            }
            return global::Integra.Vision.Engine.Resources.SR.ResourceManager.GetString("InvalidCommandElementCollection", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Invalid access to command plan
        /// </summary>
        public static string InvalidPlanAccess([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Integra.Vision.Engine.Resources.SR.InvalidPlanAccess;
            }
            return global::Integra.Vision.Engine.Resources.SR.ResourceManager.GetString("InvalidPlanAccess", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Invalid input. Syntax error: {0}. Line {1}, column {2}
        /// </summary>
        public static string SyntaxError(object arg0, object arg1, object arg2, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Integra.Vision.Engine.Resources.SR.SyntaxError, System.Tuple.Create("0", arg0), System.Tuple.Create("1", arg1), System.Tuple.Create("2", arg2));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Integra.Vision.Engine.Resources.SR.ResourceManager.GetString("SyntaxError", resourceCulture), System.Tuple.Create("0", arg0), System.Tuple.Create("1", arg1), System.Tuple.Create("2", arg2));
        }
    }
}
namespace Integra.Vision.Engine.Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class SRKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Enumeration exception ocurred. The inner exception may contain more information.
        /// </summary>
        public const string EnumerationException = "EnumerationException";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Enumerator is not implement for command
        /// </summary>
        public const string EnumeratorNotImplemented = "EnumeratorNotImplemented";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: An exception has ocurred on command interpretation. The inner exception may contain more information.
        /// </summary>
        public const string InterpretationException = "InterpretationException";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Invalid access to command element collection
        /// </summary>
        public const string InvalidCommandElementCollection = "InvalidCommandElementCollection";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Invalid access to command plan
        /// </summary>
        public const string InvalidPlanAccess = "InvalidPlanAccess";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Invalid input. Syntax error: {0}. Line {1}, column {2}
        /// </summary>
        public const string SyntaxError = "SyntaxError";
    }
}
